apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: doc185174/spring-boot-hello-world-example:latest
        ports:
        - containerPort: 8080
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: hello
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
#spec:
#  backend:
#    serviceName: default-http-backend
#    servicePort: 80
#  rules:
#    - http:
#        paths:
#        - path: /hello
#          backend:
#            serviceName: hello
#            servicePort: 8080